pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

gradle.ext.androidxMediaModulePrefix = 'media-'
gradle.ext.androidxMediaProjectName = 'media-'
apply from: file("media/core_settings.gradle")

// Exclude ffmpeg decoder on Windows as it requires WSL/unix build environment
if (org.gradle.internal.os.OperatingSystem.current().windows) {
    rootProject.children.removeAll { it.name == 'media-lib-decoder-ffmpeg' }
}

rootProject.name = "Auralis"
include ':app'
include ':musikr'
