-keep class com.auralis.musikr.metadata.Metadata { *; }
-keep class com.auralis.musikr.metadata.Properties { *; }
-keep class com.auralis.musikr.metadata.MetadataResult { *; }
-keep class com.auralis.musikr.metadata.MetadataResult$Success { *; }
-keep class com.auralis.musikr.metadata.MetadataResult$NoMetadata { *; }
-keep class com.auralis.musikr.metadata.MetadataResult$NotAudio { *; }
-keep class com.auralis.musikr.metadata.MetadataResult$ProviderFailed { *; }
