name: Android Lint

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'jetbrains'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check formatting with spotless
      run: ./gradlew spotlessCheck
    - name: Test musikr with Gradle
      run: ./gradlew musikr:testDebug
    - name: Test app with Gradle
      run: ./gradlew app:testDebug
